#!/usr/bin/env node
/**
 * dsh-release.mjs - idempotent release helper for DSH-related projects.
 *
 * One script, many projects. Each project carries a dsh-release.json at its
 * root; this script:
 *
 *   1. reads the project config + version (npm package.json, or
 *      src-tauri/tauri.conf.json when kind: "tauri")
 *   2. ensures .github/workflows/release.yml exists and matches the template
 *      (creates it if missing, OVERWRITES it if different, then commits+pushes)
 *   3. creates + pushes the tag  <tagPrefix><version>  if absent
 *      (pushing a v* tag triggers the repo's own workflow -> build+release)
 *
 * Idempotent: re-running the same version is a no-op unless --force.
 *
 * Usage:
 *   node scripts/dsh-release.mjs                 # interactive (asks Y/n)
 *   node scripts/dsh-release.mjs --dry-run       # show plan only
 *   node scripts/dsh-release.mjs --yes           # skip the prompt (agent use)
 *   node scripts/dsh-release.mjs --root <dir>    # other project root
 *   node scripts/dsh-release.mjs --force         # allow re-tagging an existing tag
 *
 * Requirements: node 20+, git on PATH. Pushing needs git credentials.
 */

import { spawnSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { createInterface } from 'node:readline'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))

/* ------------------------------------------------------------------ */
/* Workflow templates (parameterized; see dsh-release.json)           */
/* ------------------------------------------------------------------ */

// npm-package variant (default): ubuntu, pnpm, npm pack, offline zip.
function npmWorkflow(cfg) {
  const lines = []
  const tag = `${cfg.tagPrefix}*`
  lines.push(`# release.yml - generated by dsh-release (do not edit manually)`)
  lines.push(`name: release`)
  lines.push('')
  lines.push('on:')
  lines.push('  push:')
  lines.push('    tags:')
  lines.push(`      - '${tag}'`)
  lines.push('  workflow_dispatch:')
  lines.push('')
  lines.push('permissions:')
  lines.push('  contents: write')
  lines.push('')
  lines.push('jobs:')
  lines.push('  release:')
  lines.push('    runs-on: ubuntu-latest')
  lines.push('    # Job-level env: visible to step `if` conditions.')
  lines.push('    env:')
  lines.push('      NPM_TOKEN: \${{ secrets.NPM_TOKEN }}')
  lines.push('    steps:')
  lines.push('      - name: Checkout')
  lines.push('        uses: actions/checkout@v5')
  lines.push('')
  lines.push('      - name: Setup pnpm')
  lines.push('        uses: pnpm/action-setup@v6')
  lines.push('        with:')
  lines.push(`          version: ${cfg.pnpmVersion}`)
  lines.push('')
  lines.push('      - name: Setup Node')
  lines.push('        uses: actions/setup-node@v5')
  lines.push('        with:')
  lines.push('          node-version: 22')
  lines.push('          cache: pnpm')
  lines.push('')
  lines.push('      - name: Install dependencies')
  lines.push('        run: pnpm install --frozen-lockfile')
  lines.push('')
  lines.push('      - name: Assert tag matches package.json version')
  lines.push('        run: |')
  lines.push(`          PKG_VERSION="$(node -p "require('./${cfg.packageDir}/package.json').version")"`)
  lines.push(`          TAG_VERSION="\${GITHUB_REF_NAME#${cfg.tagPrefix}}"`)
  lines.push('          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then')
  lines.push('            echo "::error::tag ($TAG_VERSION) != package.json version ($PKG_VERSION)"')
  lines.push('            exit 1')
  lines.push('          fi')
  if (cfg.typecheck) {
    lines.push('')
    lines.push('      - name: Typecheck')
    lines.push('        run: ' + JSON.stringify(cfg.typecheck))
  }
  if (cfg.build) {
    lines.push('')
    lines.push('      - name: Build')
    lines.push('        run: ' + JSON.stringify(cfg.build))
  }
  lines.push('')
  lines.push('      - name: npm pack')
  lines.push('        run: |')
  lines.push('          mkdir -p dist')
  lines.push(`          (cd "$GITHUB_WORKSPACE/${cfg.packageDir}" && npm pack --pack-destination "$GITHUB_WORKSPACE/dist")`)
  lines.push('          ls -la dist/')
  if (cfg.offline && cfg.offlineScript) {
    lines.push('')
    lines.push('      - name: Assemble offline installer zip')
    lines.push('        shell: pwsh')
    lines.push('        run: |')
    lines.push(`          ./${cfg.offlineScript}`)
    lines.push('          Get-ChildItem dist | Select-Object Name, Length')
  }
  lines.push('')
  lines.push('      - name: Create / update GitHub Release')
  lines.push('        env:')
  lines.push('          GH_TOKEN: \${{ github.token }}')
  lines.push('        run: |')
  lines.push('          TAG="\${{ github.ref_name }}"')
  lines.push('          if gh release view "$TAG" --repo "\${{ github.repository }}" >/dev/null 2>&1; then')
  lines.push(`            gh release upload "$TAG" dist/*.tgz dist/*-offline-*.zip --repo "\${{ github.repository }}" --clobber`)
  lines.push('            echo "Release $TAG updated with artifacts."')
  lines.push('          else')
  lines.push(`            gh release create "$TAG" dist/*.tgz dist/*-offline-*.zip --repo "\${{ github.repository }}" --title "$TAG" --notes "dsh package $TAG — 预编译包（.tgz）与无编译环境安装包（-offline-.zip）。"`)
  lines.push('            echo "Release $TAG created."')
  lines.push('          fi')
  if (cfg.npm) {
    lines.push('')
    lines.push('      - name: Publish to npm (optional, needs NPM_TOKEN)')
    lines.push('        if: env.NPM_TOKEN != \'\'')
    lines.push('        run: |')
    lines.push('          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc')
    lines.push(`          cd "$GITHUB_WORKSPACE/${cfg.packageDir}"`)
    lines.push('          npm publish --access public')
  }
  return lines.join('\n') + '\n'
}

// Tauri desktop-app variant: windows runner, Rust + tauri build, NSIS upload.
function tauriWorkflow(cfg) {
  const lines = []
  const tag = `${cfg.tagPrefix}*`
  const verFile = cfg.versionFile || 'src-tauri/tauri.conf.json'
  lines.push(`# release.yml - generated by dsh-release (do not edit manually)`)
  lines.push(`name: release`)
  lines.push('')
  lines.push('on:')
  lines.push('  push:')
  lines.push('    tags:')
  lines.push(`      - '${tag}'`)
  lines.push('  workflow_dispatch:')
  lines.push('')
  lines.push('permissions:')
  lines.push('  contents: write')
  lines.push('')
  lines.push('jobs:')
  lines.push('  release:')
  lines.push('    runs-on: windows-latest')
  lines.push('    steps:')
  lines.push('      - name: Checkout')
  lines.push('        uses: actions/checkout@v5')
  lines.push('')
  lines.push('      - name: Setup Node')
  lines.push('        uses: actions/setup-node@v5')
  lines.push('        with:')
  lines.push('          node-version: 22')
  lines.push('')
  lines.push('      - name: Install Rust toolchain (MSVC)')
  lines.push('        uses: dtolnay/rust-toolchain@stable')
  lines.push('        with:')
  lines.push('          targets: x86_64-pc-windows-msvc')
  lines.push('')
  lines.push('      - name: Cache Rust build')
  lines.push('        uses: swatinem/rust-cache@v2')
  lines.push('        with:')
  lines.push('          workspaces: src-tauri')
  lines.push('')
  lines.push('      - name: Install Tauri CLI')
  lines.push('        run: npm install')
  lines.push('')
  lines.push('      - name: Assert tag matches tauri.conf.json version')
  lines.push('        shell: bash   # windows runners default to pwsh; the assert is bash syntax')
  lines.push('        run: |')
  lines.push(`          APP_VERSION="$(node -p "require('./${verFile}').version")"`)
  lines.push(`          TAG_VERSION="\${GITHUB_REF_NAME#${cfg.tagPrefix}}"`)
  lines.push('          if [ "$APP_VERSION" != "$TAG_VERSION" ]; then')
  lines.push('            echo "::error::tag ($TAG_VERSION) != app version ($APP_VERSION)"')
  lines.push('            exit 1')
  lines.push('          fi')
  if (cfg.typecheck) {
    lines.push('')
    lines.push('      - name: Typecheck')
    lines.push('        run: ' + JSON.stringify(cfg.typecheck))
  }
  lines.push('')
  lines.push('      - name: Build (NSIS installer)')
  lines.push('        run: ' + JSON.stringify(cfg.build || 'npm run tauri -- build'))
  lines.push('')
  lines.push('      - name: Create / update GitHub Release')
  lines.push('        env:')
  lines.push('          GH_TOKEN: \${{ github.token }}')
  lines.push('        run: |')
  lines.push('          TAG="\${{ github.ref_name }}"')
  lines.push('          $Artifacts = Get-ChildItem "src-tauri/target/release/bundle/nsis/*.exe" -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }')
  lines.push('          if ($Artifacts.Count -eq 0) { Write-Error "no NSIS installer produced"; exit 1 }')
  lines.push('          if (gh release view "$TAG" --repo "\${{ github.repository }}" >$null 2>&1) {')
  lines.push('            gh release upload "$TAG" $Artifacts --repo "\${{ github.repository }}" --clobber')
  lines.push('            echo "Release $TAG updated with artifacts."')
  lines.push('          } else {')
  lines.push('            gh release create "$TAG" $Artifacts --repo "\${{ github.repository }}" --title "$TAG" --notes "dsh-desktop $TAG — Windows 安装包（NSIS, per-user）。"')
  lines.push('            echo "Release $TAG created."')
  lines.push('          }')
  return lines.join('\n') + '\n'
}

function workflowTemplate(cfg) {
  return cfg.kind === 'tauri' ? tauriWorkflow(cfg) : npmWorkflow(cfg)
}

/* ------------------------------------------------------------------ */
/* Helpers                                                            */
/* ------------------------------------------------------------------ */
function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', ...opts })
  if (r.error) throw r.error
  return { ok: r.status === 0, status: r.status, stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim() }
}

function git(args, opts = {}) {
  return run('git', args, opts)
}

function fail(msg) {
  console.error(`[dsh-release] 错误: ${msg}`)
  process.exit(1)
}

function log(msg) { console.log(`[dsh-release] ${msg}`) }

async function ask(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout })
  const answer = await new Promise((resolveAnswer) => rl.question(question, resolveAnswer))
  rl.close()
  return answer.trim().toLowerCase()
}

/* ------------------------------------------------------------------ */
/* Config                                                             */
/* ------------------------------------------------------------------ */
function probeConfig(root) {
  // No dsh-release.json: probe for a package.json with dsh fingerprints.
  const candidates = [
    join(root, 'packages', 'ide', 'package.json'),
    join(root, 'package.json'),
  ]
  for (const p of candidates) {
    if (!existsSync(p)) continue
    try {
      const pkg = JSON.parse(readFileSync(p, 'utf8'))
      const looksLikeDsh = pkg.dsh?.client || pkg.dependencies?.zod || pkg.name?.startsWith('dsh-')
      if (looksLikeDsh) {
        const dir = dirname(p).replaceAll('\\', '/')
        return {
          packageDir: dir.slice(root.length + 1) || '.',
          packageName: pkg.name || 'dsh-package',
          tagPrefix: 'v',
          offline: false,
          offlineScript: null,
          typecheck: null,
          build: null,
          npm: false,
          pnpmVersion: 11,
          _probed: true,
        }
      }
    } catch { /* try next */ }
  }
  return null
}

function loadConfig(root) {
  const cfgFile = join(root, 'dsh-release.json')
  let cfg = null
  if (existsSync(cfgFile)) {
    cfg = JSON.parse(readFileSync(cfgFile, 'utf8'))
    log(`配置: ${cfgFile}`)
  } else {
    cfg = probeConfig(root)
    if (cfg) log('配置: 未找到 dsh-release.json，已从 package.json 探测默认值')
    else fail('未找到 dsh-release.json，也无法自动探测项目配置（请添加 dsh-release.json 或用 --root 指定项目根）')
  }
  const defaults = {
    tagPrefix: 'v', offline: false, offlineScript: null,
    typecheck: null, build: null, npm: false, pnpmVersion: 11,
    kind: 'npm', versionFile: null,
  }
  cfg = { ...defaults, ...cfg }
  if (!cfg.packageDir || !cfg.packageName) fail('配置缺少 packageDir / packageName')
  return { cfg, cfgFile: existsSync(cfgFile) ? cfgFile : null }
}

// Read the project version: tauri.conf.json for kind "tauri", else package.json.
function readVersion(root, cfg) {
  if (cfg.kind === 'tauri') {
    const verFile = join(root, cfg.versionFile || 'src-tauri/tauri.conf.json')
    if (!existsSync(verFile)) fail(`找不到版本文件 ${verFile}`)
    return JSON.parse(readFileSync(verFile, 'utf8')).version
  }
  const pkgFile = join(root, cfg.packageDir, 'package.json')
  if (!existsSync(pkgFile)) fail(`找不到 ${cfg.packageDir}/package.json`)
  return JSON.parse(readFileSync(pkgFile, 'utf8')).version
}

/* ------------------------------------------------------------------ */
/* Main                                                               */
/* ------------------------------------------------------------------ */
async function main() {
  const args = process.argv.slice(2)
  const get = (name) => { const i = args.indexOf(name); return i >= 0 && args[i + 1] ? args[i + 1] : null }
  const has = (name) => args.includes(name)
  const root = resolve(get('--root') || process.cwd())
  const dryRun = has('--dry-run')
  const yes = has('--yes')
  const force = has('--force')
  const emit = get('--emit-workflow')

  if (!existsSync(join(root, '.git'))) fail(`不是 git 仓库: ${root}`)

  const { cfg } = loadConfig(root)
  const version = readVersion(root, cfg)
  if (!version) fail('项目缺少 version')
  const tag = `${cfg.tagPrefix}${version}`

  // Dev helper: materialize the generated workflow without any git operation.
  if (emit) {
    const rendered = workflowTemplate(cfg)
    writeFileSync(resolve(emit), rendered, 'utf8')
    log(`workflow written to ${resolve(emit)} (no git changes)`)
    return
  }

  // --- tag existence (fetch first so remote tags are visible) -------
  git(['fetch', '--tags', '--quiet'])
  const tagExists = git(['rev-parse', '-q', '--verify', `refs/tags/${tag}`]).ok

  // --- workflow: render template, compare, decide --------------------
  const wfRel = '.github/workflows/release.yml'
  const wfFile = join(root, wfRel)
  const rendered = workflowTemplate(cfg)
  const wfExists = existsSync(wfFile)
  const wfSame = wfExists && readFileSync(wfFile, 'utf8') === rendered
  const wfAction = !wfExists ? 'create' : wfSame ? 'keep' : 'overwrite'

  // --- summary --------------------------------------------------------
  log(`项目: ${cfg.packageName}  @ ${root}`)
  log(`版本: ${version}  →  tag: ${tag}  ${tagExists ? '(已存在)' : '(不存在)'}`)
  log(`workflow ${wfRel}: ${wfAction}`)
  if (wfAction === 'overwrite') log('  现有 workflow 与模板不一致，将覆盖（dsh-release.json 为真相来源）')
  if (dryRun) { log('--dry-run: 以上为执行计划，未做任何改动。'); return }

  // --- confirm ----------------------------------------------------------
  if (!yes) {
    const q = `确认发布 ${cfg.packageName} ${version}？\n  将 ${wfAction} workflow，${tagExists ? `tag ${tag} 已存在（--force 可强制重建重发）` : `创建并推送 tag ${tag}`}\n  (Y/n) `
    const a = await ask(q)
    if (a !== 'y' && a !== 'yes' && a !== '') { log('已取消。'); return }
  }

  // --- apply workflow change (independent of tag state) -----------------
  if (wfAction !== 'keep') {
    writeFileSync(wfFile, rendered, 'utf8')
    log(`已${wfAction === 'create' ? '创建' : '覆盖'} ${wfRel}`)
    const identityOk = git(['config', 'user.name']).ok && git(['config', 'user.email']).ok
    if (!identityOk) {
      git(['config', 'user.name', 'dsh-release'])
      git(['config', 'user.email', 'dsh-release@users.noreply.github.com'])
    }
    git(['add', wfRel])
    const commit = git(['commit', '-m', `ci: update release workflow (dsh-release ${version})`])
    if (!commit.ok && !commit.stderr.includes('nothing to commit')) {
      fail(`workflow 提交失败: ${commit.stderr}`)
    }
    const branch = git(['branch', '--show-current']).stdout
    if (branch) {
      const push = git(['push', 'origin', `refs/heads/${branch}:refs/heads/${branch}`])
      if (!push.ok) fail(`推送 workflow 到 ${branch} 失败: ${push.stderr}（可能需要 git 凭据/代理）`)
      log(`workflow 已推送到 ${branch}`)
    } else {
      log('警告: 无法确定当前分支，workflow 改动未推送')
    }
  }

  // --- create / rebuild + push tag ----------------------------------------
  if (tagExists && !force) {
    log(`tag ${tag} 已存在，未重复创建。`)
  } else if (tagExists && force) {
    git(['push', 'origin', `:refs/tags/${tag}`])
    git(['tag', '-f', tag])
    const push = git(['push', 'origin', tag])
    if (!push.ok) fail(`强制重建 tag ${tag} 失败: ${push.stderr}`)
    log(`已强制重建并推送 tag ${tag} → 将触发该仓库的 release workflow`)
  } else {
    git(['tag', tag])
    const push = git(['push', 'origin', tag])
    if (!push.ok) fail(`推送 tag ${tag} 失败: ${push.stderr}（可能需要 git 凭据/代理）`)
    log(`已创建并推送 tag ${tag} → 将自动触发该仓库的 release workflow`)
  }

  log('完成。请到 GitHub Actions 查看 release 运行；Release 产物将挂在 tag 对应的 Release 页面。')
}

main().catch((e) => fail(e instanceof Error ? e.message : String(e)))
